apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: joshcausey/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
manifests:
  rawYaml:
    - infra/k8s/*
